version: '3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./app:/usr/src/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "3003:3000"

  rabbitmq:
    image: rabbitmq:3.7.4
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest