version: '3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./app:/usr/src/app
    networks:
      - app-network
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.4
    networks:
      - app-network

networks:
  app-network:
    driver: bridge