version: '3'

services:

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./app:/usr/src/app
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    ports:
      - "3003:3000"

  rabbitmq:
    build:
      context: ./docker/rabbitmq
    volumes:
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
       - 5672:5672
       - 15672:15672

  redis:
    image: redis:alpine